apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/raelga/argocd-poc-examples.git
    targetRevision: HEAD
    path: kuard/manifests

  syncPolicy:
    validate: true
    automated:
      # Enable automatic sync when the live cluster's state deviates from the state defined in Git
      selfHeal: true
      # Delete resources when Argo CD detects the resource is no longer defined in Git.
      prune: true

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-examples
